# Generated by Django 5.0.14 on 2026-03-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loan_guarantor_loanguarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='rollover_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LoanRollover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rolled_on', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollovers', to='loans.loan')),
            ],
            options={
                'ordering': ['rolled_on'],
            },
        ),
    ]
