# Generated by Django 5.1.4 on 2026-04-20 04:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_rollover'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='late_penalty_months',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of overdue months for which the penalty has been applied.'),
        ),
        migrations.AddField(
            model_name='loan',
            name='late_penalty_per_month',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Fixed monthly penalty amount (10% of original principal).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='loanguarantor',
            name='amount_guaranteed',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='loanrollover',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='loanrollover',
            name='new_interest',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='loanrollover',
            name='new_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
