# Generated by Django 5.0.14 on 2026-05-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfarecontribution',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='M-Pesa confirmation code (required for M-Pesa payments).', max_length=20),
        ),
        migrations.AddField(
            model_name='welfarecontribution',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='welfaredisbursement',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='M-Pesa confirmation code (required for M-Pesa payments).', max_length=20),
        ),
        migrations.AddField(
            model_name='welfaredisbursement',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='welfaresupportcontribution',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='M-Pesa confirmation code (required for M-Pesa payments).', max_length=20),
        ),
        migrations.AddField(
            model_name='welfaresupportcontribution',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa')], default='cash', max_length=10),
        ),
    ]
