# Generated by Django 5.0.14 on 2026-03-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penalty',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
