# Generated by Django 5.0.14 on 2026-05-01 10:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_unique_payment_per_loan_date_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='M-Pesa confirmation code (required for M-Pesa payments).', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
