# Generated by Django 5.1.4 on 2026-04-26 14:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_member_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearEndWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.PositiveIntegerField(unique=True)),
                ('amount_withdrawn', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_shared', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='year_end_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-financial_year'],
            },
        ),
        migrations.CreateModel(
            name='YearEndMemberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('continuing', 'Continuing'), ('exiting', 'Exiting')], default='continuing', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_end_statuses', to='members.member')),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_statuses', to='yearend.yearendwithdrawal')),
            ],
            options={
                'ordering': ['member__name'],
                'unique_together': {('withdrawal', 'member')},
            },
        ),
        migrations.CreateModel(
            name='MemberInterestShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_shares', to='members.member')),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_shares', to='yearend.yearendwithdrawal')),
            ],
            options={
                'ordering': ['member__name'],
                'unique_together': {('withdrawal', 'member')},
            },
        ),
    ]
