# Generated by Django 5.1.4 on 2026-04-22 21:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_editable_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
